# Generated by Django 5.2.12 on 2026-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='e_book_file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_ebook',
            field=models.BooleanField(default=False),
        ),
    ]
